### ISSUE TITLE
[BUG] Error retrieving user: java.util.concurrent.CompletionException: java.lang.RuntimeException

### ISSUE THREAD

**Issue by creamgod45** [GeorgeV220/SkinOverlay#64]
server: 1.18.2 purpur
plugins: version. 6.2.0
```
[SkinOverlay] Error retrieving user:
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.InvalidClassException: com.georgev22.skinoverlay.library.maps.ConcurrentObjectMap; local class incompatible: stream classdesc serialVersionUID = 1003981980602493804, local class serialVersionUID = -2802251752999929943
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.RuntimeException: java.io.InvalidClassException: com.georgev22.skinoverlay.library.maps.ConcurrentObjectMap; local class incompatible: stream classdesc serialVersionUID = 1003981980602493804, local class serialVersionUID = -2802251752999929943
        at com.georgev22.skinoverlay.library.utilities.EntityManager.lambda$load$1(EntityManager.java:80) ~[skinoverlay-6.2.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
Caused by: java.io.InvalidClassException: com.georgev22.skinoverlay.library.maps.ConcurrentObjectMap; local class incompatible: stream classdesc serialVersionUID = 1003981980602493804, local class serialVersionUID = -2802251752999929943
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597) ~[?:?]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051) ~[?:?]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
        at java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2606) ~[?:?]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2457) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2257) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:509) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:467) ~[?:?]
        at com.georgev22.skinoverlay.library.utilities.Utils.deserializeObject(Utils.java:523) ~[skinoverlay-6.2.0.jar:?]
        at com.georgev22.skinoverlay.library.utilities.EntityManager.lambda$load$1(EntityManager.java:76) ~[skinoverlay-6.2.0.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
```
server plugins:
AdvancedChests v28.0
AdvancedCrates v3.9.6
AdvancedEnchantments v9.2.9
Adventageous v1.2.1
AquaticCrates v2.3.9
AsyncWorldEdit v3.9.4
AuctionHouse v2.99.0
AuxProtect v1.2.6
BannerBoard v1.11.19
BannerMaker v2.3.2
BattlePass v3.17.9
BetterBackpacks v1.2.2-BETA
BettingGames v2.4.2
BKCommonLib v1.20.1-v1
Blackjack v1.7
BountyHunters v2.5.1
CancelFriendRequest v1.0.6-RELEASE
CGCommandTOGui v1.0.0
CGInvisibleItemFrame v1.3.3
ChatBubbles v1.19.2.a.6
ChestProtect v5.9.2
ChestSort v13.6.3
Chunky v1.3.92
CinematicStudio v1.4.3-r8
Citizens v2.0.31-SNAPSHOT (build 3091)
CitizensGUI v1.11
CMI v9.6.0.6
CMIEInjector v1.0.2.3
CMILib v1.3.1.1
CoreProtect v21.3
CosmeticsCore v1.2.1
Cupido v1.0.4
CustomCrafting v4.16.8.0
CustomDrops v1.12.0
CustomPiglinsTrades v3.9.94
CustomUniverse v1.0.9
CustomWings v4.1.3
CyberWorldReset v1.4.7
DecentHolograms v2.8.3
Dungeons v3.1.1
DynamicShop v3.15.2
eco v6.63.0
EcoJobs v3.19.2
EcoSkills v3.7.2
eGlow v3.2.3
EliteMobs v8.5.4
ExecutableBlocks v3.9.94
ExecutableItems v5.9.94
ExtractableEnchantments v9.9
F3NPerm v3.3
FarmingUpgrade v1.4.0
FriendsAPIForPartyAndFriends v1.5.4-RELEASE
FRL v1.0.4-RELEASE
GCore v8.46.0
GlowAPI v1.5.7-SNAPSHOT
GPS v2.19.22
GPS-Quests v1.9
HappyHUD v0.3.5-SNAPSHOT
HeadDatabase v4.17.3
HMCCosmetics v2.4.8
IA-For-PAF v1.0.5-RELEASE
InteractiveBoard v19.9
InteractiveChat v4.2.7.0
ItemRecycler v1.3.5
ItemsAdder v3.5.0c
JetsMinions v7.9.1
LagAssist v2.29.0
libreforge v4.20.2
LibsDisguises v10.0.37
LightAPI vbukkit-5.3.0 (build SNAPSHOT)
LoneLibs v1.0.25
Lootin v6.3
MCPets v3.1.1
MLib v0.0.3
MMOCore v1.12-SNAPSHOT
MMOItems v6.9.4-SNAPSHOT
ModelEngine vR3.1.8
MultiWorld v5.2.8
Mute-All-For-PAF v1.0.3-RELEASE
MyPet v3.12
MythicCrucible v1.6.0-SNAPSHOT
MythicLib v1.6-SNAPSHOT
MythicMobs v5.3.0-SNAPSHOT-2e3c2bf1
MythicMobsGUI v1.6.2
NBTAPI v2.11.3
NFAchievements v1.0.0
NoteBlockAPI v1.6.2-SNAPSHOT
OpenAudioMc v6.8.5
PacketListenerApi v3.9.10-SNAPSHOT
PartyAndFriends v1.0.237-E-For-Spigot
Physicsgun v1.4
PlaceholderAPI v2.11.3
PlayerParticles v8.3
PlayerPoints v3.2.5
PluginHiderFixer v1.2.6
PlugManX v2.3.3
PrefixesPerms-For-PAF v1.0.5-RELEASE
PremiumVanish v2.8.9
ProtocolLib v5.1.0-SNAPSHOT-652
QualityArmory v2.0.9
QuestCreator v6.46.0
Quests v4.8.2-b416
QuickShop v5.1.2.2
RealisticVillagers v3.0.1
RedeemableCodes vBuild 38
Residence v5.1.1.3
ReviveMe v3.2.5
RotatingHeads2 v1.0.4
Roulette v1.9.5
RPGInventory v1.8
SCore v3.9.94
ServerFunUtils v1.0.0
ServerListPlus v3.5.0
ServerRestorer v1.0.39
ServerTours v2.0.11
Shopkeepers v2.17.1
SkinOverlay v6.2.0
SlotBot v1.1.8
spark v1.10.29
Spigot-Party-API-PAF v1.0.5-RELEASE
Stocks v1.9.6
SuperHarvest v1.3.3
TAB v4.0.1
TheSearch v1.22.1
TradeMe v6.1.3.4
Train_Carts v1.20.1-v1
TreasureChestX v1.0
TreeAssist v7.3.41
UltimateAutoRestart vBuild 54a
UltimateCatcher vmaven-version-number
UltimateStacker v2.3.0
UltraCustomizer v2.1.0
UltraPermissions v5.4.7
Vault v1.7.3-b131
Vehicles v14.0
VehiclesPlusPro v2.4.3
Websocket v4
WG-GUI v1.6
WildLoaders v2022.7-b68
WirelessRedstone v0.4.4.3
WolfyUtilities v4.16.12.0
WorldEdit v7.2.13+46576cc
WorldGuard v7.0.7+216b061
YamipaPlugin v1.2.11

**Comment by creamgod45** [comment]
trigger onplayerjoin

**Comment by GeorgeV220** [comment]
did you update the plugin from an older release ? 6.x is not compatible with 5.0 and some times minor releases are not compatible with the previous ones, delete your user and skin data.

**Comment by creamgod45** [comment]
thanks done
