### ISSUE TITLE
[BUG] SkinOverlay does not work.

### ISSUE THREAD

**Issue by MatsCraft1** [GeorgeV220/SkinOverlay#71]
I can't apply any overlays. When entering /soverlay overlay (myskinname) Augustus15 it throws no error, but says everything has been succesful - which isn't the case. My skin doesn't change.
When entering "/soverlay clear" the console throws this error:

[20:15:29] [Server thread/INFO]: Augustus15 issued server command: /soverlay clear
[20:15:29] [ForkJoinPool.commonPool-worker-3/ERROR]: [SkinOverlay] Error generating or retrieving the skin:
com.georgev22.skinoverlay.exceptions.SkinException: ImageSupplier cannot be null
        at com.georgev22.skinoverlay.handler.SkinHandler.lambda$retrieveOrGenerateSkin$0(SkinHandler.java:94) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]       

Server Version:
[20:17:19] [Server thread/INFO]: This server is running CraftBukkit version 3926-Spigot-dba3cdc-ffb1319 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)
[20:17:19] [Server thread/INFO]: Checking version, please wait...

Server Plugins:
[20:17:55] [Server thread/INFO]: Plugins (10): HiddenNameplates, CrackShot, FastAsyncWorldEdit (WorldEdit), Multiverse-Core, ProtocolLib (Errored), WorldGuard, AdvancedNMotd, SkinsRestorer, WorldGuardEvents, SkinOverlay

WorldGuard Report:
https://paste.enginehub.org/GgRdLXdtu.report

**Comment by MatsCraft1** [comment]
Addition:

When logging in, console throws this error:

[20:14:21] [ForkJoinPool.commonPool-worker-3/ERROR]: [SkinOverlay] Error:
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at com.georgev22.skinoverlay.handler.handlers.SkinHandler_Unsupported.lambda$wrapper$2(SkinHandler_Unsupported.java:62) ~[?:?]
        at com.google.common.collect.Multimap.lambda$forEach$0(Multimap.java:348) ~[guava-32.1.2-jre.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.google.common.collect.Multimap.forEach(Multimap.java:348) ~[guava-32.1.2-jre.jar:?]
        at com.georgev22.skinoverlay.handler.handlers.SkinHandler_Unsupported.wrapper(SkinHandler_Unsupported.java:62) ~[?:?]
        at com.georgev22.skinoverlay.handler.handlers.SkinHandler_Unsupported.getGameProfile(SkinHandler_Unsupported.java:57) ~[?:?]
        at com.georgev22.skinoverlay.utilities.player.PlayerObject.gameProfile(PlayerObject.java:155) ~[?:?]
        at com.georgev22.skinoverlay.utilities.player.PlayerObject.lambda$playerJoin$3(PlayerObject.java:281) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
        ... 7 more

**Comment by GeorgeV220** [comment]
Hello, try the latest release
