### ISSUE TITLE
Problem with /wear

### ISSUE THREAD

**Issue by xNarCoZz** [GeorgeV220/SkinOverlay#72]
Hello,

I have a minecraft server with paper 1.20.2 and when I use the /wear I have this error

[19:43:36 INFO]: xNarCoZz issued server command: /wear policeman
[19:43:36 WARN]: [SkinOverlay] Plugin SkinOverlay v1.7.1 generated an exception while executing task 35091
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer net.minecraft.server.level.EntityPlayer.getBukkitEntity()'
        at dev.piglin.skinoverlay.SkinOverlay.lambda$setSkin$28(SkinOverlay.java:157) ~[SkinOverlays-1.8.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

How can I fix?

**Comment by xNarCoZz** [comment]
Now it's give me this error when I do the command /wearurl

[20:24:14 INFO]: xNarCoZz issued server command: /wearurl https://minecraft.novaskin.me/download/1740783035
[20:24:14 ERROR]: [SkinOverlay] Error:
java.io.IOException: Server returned HTTP response code: 403 for URL: https://minecraft.novaskin.me/download/1740783035
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2022) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at java.net.URL.openStream(URL.java:1161) ~[?:?]
        at com.georgev22.skinoverlay.commands.SkinOverlayCommand.url(SkinOverlayCommand.java:139) ~[skinoverlay-7.0.0.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.georgev22.skinoverlay.commands.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[skinoverlay-7.0.0.jar:?]
        at com.georgev22.skinoverlay.commands.acf.BaseCommand.executeCommand(BaseCommand.java:578) ~[skinoverlay-7.0.0.jar:?]
        at com.georgev22.skinoverlay.commands.acf.BaseCommand.execute(BaseCommand.java:513) ~[skinoverlay-7.0.0.jar:?]
        at com.georgev22.skinoverlay.commands.acf.RootCommand.execute(RootCommand.java:99) ~[skinoverlay-7.0.0.jar:?]
        at com.georgev22.skinoverlay.commands.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84) ~[skinoverlay-7.0.0.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-318]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
